---

- name: Apt update
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
    autoclean: true
    autoremove: true
  when: ansible_os_family == "Debian"

- name: Ensure crowdsec dependencies
  ansible.builtin.package:
    name:
      - gnupg curl

- name: Install dependencies (Debian Family)
  apt:
    name:
      - apt-transport-https
  when: ansible_os_family == "Debian"

- name: Add an apt signing key
  ansible.builtin.apt_key:
    url: https://packagecloud.io/crowdsec/crowdsec/gpgkey

- name: Add apt repo
  ansible.builtin.apt_repository:
    repo: deb https://packagecloud.io/crowdsec/crowdsec/{{ ansible_distribution|lower }}/ {{ ansible_distribution_release|lower }} main
    state: present
    filename: crowdsec_crowdsec
  when: ansible_os_family == "Debian"

- name: Install Crowdsec
  ansible.builtin.apt:
    name:
      - crowdsec
  when: ansible_os_family == "Debian"

- name: Deploy main config
  ansible.builtin.template:
    src: etc/crowdsec/config.yaml.j2
    dest: /etc/crowdsec/config.yaml
    owner: root
    group: root
    mode: 0644
  notify: restart crowdsec

- name: Deploy whitelist
  ansible.builtin.template:
    src: etc/crowdsec/parsers/s02-enrich/mywhitelist.yaml.j2
    dest: /etc/crowdsec/parsers/s02-enrich/mywhitelist.yaml
    owner: root
    group: root
    mode: 0644
  when: crowdsec_whitelist.enabled
  notify: restart crowdsec

- name: Flush handlers to apply config
  meta: flush_handlers

- name: Register agent(s)
  include_tasks: register_agent.yml
  when:
    - crowdsec_delegate_server_hostname != inventory_hostname

- name: Register distributed bouncers(s)
  include_tasks: add_bouncer.yml
  when:
    - crowdsec_bouncer.enabled
